### PR TITLE
fix: kill jobs with sigint first

### LINKED ISSUE #521: Processes are not being properly terminated
Ok so this issue is a tricky one I've been debugging for a few hours and relates closely to https://github.com/neovim/neovim/issues/24567

## Problem

So basically today I noticed my machine tanking whilst working on a python project setup to run `pylint` with nvim-lint. After running `ps x` I noticed there were 100's of zombie `pylint` processes.

I debugged `lua/lint.lua` and found nothing wrong with the logic so I dug deeper.

What I found can be illustrated with:

- create a script called `test.sh` with the contents:
   ```bash
   #!/bin/bash
   sleep 1000
   ```
- `chmod +x test.sh`
- `./test.sh`
- switch to another terminal
- `ps x`
   should show something like
   ```
   ...
   90794 pts/30   S+     0:00 /bin/bash ./test.sh
   90795 pts/30   S+     0:00 sleep 1000
   ...
   ```
- `kill -15 90794` (`kill -9 90794` does the same thing)
- `ps x`
   still shows:
   ```
   ...
   90795 pts/30   S+     0:00 sleep 1000
   ...
   ```

So basically running `sigterm` on a `pid` of a running script doesn't kill any of its subprocesses.

And this is exactly what was happening with `nvim-lint` and `pylint` since `pylint` is implemented as a python script with the contents:
```python
#!/devtools/homebrew/opt/python@3.11/bin/python3.11
# -*- coding: utf-8 -*-
import re
import sys
from pylint import run_pylint
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run_pylint())
```

## Possible solutions

Launching the process `detached = true` and switching `sigterm` to `sigkill` will resolve this, however `sigkill` is quite aggressive.

So additionally, I propose we first issue `sigint` and then set up a timer until the process is closed. If it isn't closed by a certain duration, then hit it with a `sigkill`.

### PR DESCRIPTION
**Pull request by lewis6991**
Closes #521

Note with this change, if Nvim crashes any running processes will be orphaned.

### CODE REVIEW

File: lua/lint.lua [hunk 1]
```diff
@@ -304,7 +319,9 @@ function M.lint(linter, opts)
     stdio = { stdin, stdout, stderr },
     env = env,
     cwd = opts.cwd or linter.cwd or vim.fn.getcwd(),
-    detached = false
+    -- Linter may launch child processes so set this as a group leader and
+    -- manually track and kill processes as we need to.
+    detached = true
```
Comment (mfussenegger) [inline lua/lint.lua:324]: I think this would cause issues on windows. See https://github.com/mfussenegger/nvim-lint/commit/4fb01e09af04e2ec953aa177f38ea6ded62e97eb


Would changing from sigterm to sigint be good enough?

Comment (lewis6991) [reply lua/lint.lua:324]: Hard to say, sigint is a much weaker signal so I would say we should ensure anything is closed with either sigterm or sigkill.

If windows has issues then we can force `detached` to false on that platform. It most definitely doesn't follow the same semantics anyway.

Comment (lewis6991) [reply lua/lint.lua]: I've updated so we do not detach on windows.

**Comment by mfussenegger** [comment]
Thanks
